default[:cloudfiles][:user] = "root"
default[:cloudfiles][:group] = "root"
default[:cloudfiles][:homedir] = "/root"
default[:cloudfiles][:bzr_email] = "you@example.com"
default[:cloudfiles][:bzr_branch] = "lp:swift"
default[:cloudfiles][:launchpad_login] = "gimme"
default[:cloudfiles][:mount_path] = "/srv/node"
default[:cloudfiles][:mounted_drives] = "7"
